language: ruby
rvm:
  - "2.0.0p247"
branches:
  only:
    - master
install: 
	- "gem install jekyll"
script: jekyll serve --no-watch
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: showmesomethingcool.com
    endpoint: http://showmesomethingcool.com.s3-website-us-west-2.amazonaws.com/
    region: us-west-2
    skip_cleanup: true
    local-dir: _site
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always