language: ruby
rvm:
- 2.0.0-p247
branches:
  only:
  - master
sudo: required
install:
- bundle install
script:
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: secure1
  secret_access_key: secure2
  bucket: showmesomethingcool.com
  endpoint: showmesomethingcool.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  skip_cleanup: true
  upload-dir: _site
  acl: public_read
  detect_encoding: true
  cache_control: max-age=31536000
  expires: '2015-12-21 00:00:00 -0000'
notifications:
  email:
  - team@variantstudios.com
env:
  global:
  - secure: m9M2CtF6CFBi24laH+dPVDXYZbgyoO75TP7VPpqwqSHHfuO7AwNcLbLilisJk603REAK7u2W3XFNbBVWQqe2SuFIar0ilqYunZ/VfU2q6sKD//sCLahHYlkO4oeeegSHJSVimIGEoC365u0s400YyOzDB5i8XpEWkCCI2snYgONt01AZS3YN1wQOpP2lOM4Gq0P4SdaDj5ugmqu5Fn1o8f/Z6zer0iC15F6BJK+9nTHNZqZVxBJL/rMZSYi27akYsjHwwaSTKJKGMi03bZ/LihwCSh8Luo7d3KGP209Qfn+nV29xbF8HMNaBtAN9WZuhL19V/luZVuI1pL3HmeMHmxGPuQp38ueGvx0a51wuhrIGdDpMeuT+F3ycJKFoCJ9f8YnCZnu9l4EiyexzQ9wqQ+PvlvqUQqZGOHSmAgL9XbOFsZJVZtz/m08QGY/Gw4qC91EM/3gvZFbXF9G80shvLWpLgGgz6OycwidEjuY32G2s9EEV/FwS2alvbtGR1Jp/uOvjZxAO3nqArkwNlMWKvIBDLRsHSr209MJYs6Y+mdnwAI5fUALfBcPIQO5/hLHT8sOp847dcZ8qaTGQ28zVth5imLUY5o29MNuz81bRxjshggHx7u0YJKthswd8FS6spMA7BAdVP9SxkaglhuvtK2aPlst7aeCI4rNV9UsiAj4=
  - secure: ytqP2tD9XGKnu1eaZXmXRF4AIs/DOnWmQQh0Vnw80k/mcr0JhmA6tKnftfOIa2GEGsTXIdRpEe/FR7/jihBzsodkSdYM/DNt75Q+3GOoWSKpeau5ZabE/BLpGwZRwl4y3Y7g/Ezyhjs/c9DUrjakb3fIubdaGqyHcOKykt48IB2SKI0BMqSfh76b9NJQwT1g7N/A74oHgafM4X47ZFiXVFDRcGFj8IQpleqT/F5h3iDZBJBkEIW3m7+NF3wVp/HqMAUjRsO33aeL2Zrmto+elOpy4gBDJtz+T5/JPuB0t+N8QFI/jQYTETe1df4j3o2gi0odiWBN3Vw7f831kFmTybdv/BaSajWF1Vs0Y7DezReJS1gys8R4jVJaGbLdlg6cokNEek1Aa0sh7mUq0k6mxVkzteppC76GbB+mXfkVEh2wZp7tf5hi7MBYSH/dXu2U/WpllOIcyc2vBMZWdXNdSFbalszKLqeIx7SOKEJgK3JjmkprJX1iGiA1wlzobmLnWJ2zQTUsNIDpaBXXtNtXwR6ujPPyT2IalEQtvyyhDiP+pT0Wf/YOKQLwv03S9SdIHxArypp+1HVs4ZxOUsYDaWI6xcivxI+B0Yr8fuFk5ohlm6k5EpWf5xR/iMdaWZec+do3QYyI0vjAoBpTixvB7qUFHYdRP9ahUbGs05WzVXE=
