language: ruby
rvm:
- 2.0.0-p247
branches:
  only:
  - master
sudo: required
install:
- bundle install
script:
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: secure
  secret_access_key: secure
  bucket: showmesomethingcool.com
  endpoint: showmesomethingcool.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  skip_cleanup: true
  upload-dir: _site
  acl: public_read
  detect_encoding: true
  cache_control: max-age=31536000
  expires: '2015-12-21 00:00:00 -0000'
notifications:
  email:
  - team@variantstudios.com
env:
  global:
    secure: juW9eF4Yy4mRaBK63vFKFA6qpAyfo+H4W8fg8Wzw2QLkaG9t9AgVxT9n3MIExPpPsSPWIoeZRpxuk59crlLejfkIoxXpnuLYsZmvsuPSNwko24AOt/cIuOTNyYeG4oLsMkXNyAX6aOTHkj//4EyiqZNh6i/WoSDgshnCS5kkJG55H5PvGQjhqdNPms/fdUQoX1jtUkNdpjxKynq/oB3kOPKjQFaFYAGtih2pKO8yljMNCVRt5S2Q6mzy8uE27NRHFKmKjQ8W1JoNmOYZQXNUZSrTiXVSco8NIAFV4Vw7tn97FRX5HnG8P22OJSh0gIv/flCBofI+t6GROfTn6rnvBZoJ5CqQDRYPptVoFtLjk/7xbsSDA7jws2FxrV8UolwGQ64CHAbA9C35mJ3XjGbeuTmk1iQAOwzFqed2Y4UieCDqEbuGxcDpWpBl8ooKZVeRi5JGxmFM7TaTbGKpVdOjLXnEBerVLe6AuL3riMHU4xvesVMD4RygTJwVB9l9lR7Or89IWKkGGu3aNgg2oVzGoPut9CqdsI9vdUdvE1VDGenu0XQd19WbHVy0Muu1L7IDt7CYJa+loz5BTHrN61GlHzH4hD29BaOFrq/17WbC3OBQzfZc/8AzDZi5u4iE+yGpNqucrL8Q+D5//0Qg1T06DseFA+6Gurp0KzYWBg7zgRA=
